In [1]:
import numpy as np

In [22]:
import numpy as np

marks = np.array([
    
        
            [70, 80, 90, 60, 75]
            
        
    ])

# (marks.ndim)
# (marks.shape)
(marks[0,1])

np.int64(80)

In [31]:
marks=np.array([
    [
    [12,13,14,15],
    [23,21,24,55],
],
    [
    [56,78,45,67],
    [23,45,67,12]
    ]
    ])
# marks.ndim    
marks.shape

(2, 2, 4)

In [33]:
arr=np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)

In [35]:
data=np.array([
    [12,13,14,14,13],
    [34,45,567,78,89]
])

print(data.shape)
print(data.size)

(2, 5)
10

In [38]:
data=np.array([
    [1],
    [1]
    ])
print(data.dtype)

int64

In [46]:
data=np.array([10,20,30,40,50])
data1=[10,20,30,40,50]
print(data.ndim)
print(data.size)
print(data.shape)
print(data.dtype)
print(data) # np.array u can use to remove the commas to the output
print(data1)# commass are allowed

1
5
(5,)
int64
[10 20 30 40 50]
[10, 20, 30, 40, 50]

In [52]:
arr=np.array([
    [12,13,13,13,13],
    [45,67,79,76,56],
    [45,34,45,45,56,]

])
arr1=[12,13,13,13,13,
     45,67,79,76,56,
     45,34,45,45,56,]

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr1)
# print(arr1.dtype)

(3, 5)
2
15
int64
[12, 13, 13, 13, 13, 45, 67, 79, 76, 56, 45, 34, 45, 45, 56]

In [54]:
data11=np.array([
    [
        [12,12,12,12,12,12],
        [12,12,12,12,12,12,]
    ],
    [
        [12,12,12,12,12,12],
        [12,12,12,12,12,12]
    ]
])
print(data11.shape)
print(data11.ndim)
print(data11.size)
print(data11.dtype)

(2, 2, 6)
3
24
int64

In [58]:
arr=np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
arr=np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]

In [67]:
arra=np.eye(8)
print(arra)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

In [80]:
#randam variables

arr=np.random.rand(10)
print(arr)

[0.02559376 0.07732625 0.71368233 0.13834503 0.53362854 0.71579424
 0.16053621 0.71847687 0.36681049 0.69071375]

In [83]:
# shape
arr=np.random.rand(2,5)
print(arr)
print(arr.shape)
print(arr.ndim)

[[0.08170145 0.78291929 0.96621606 0.14039218 0.45260792]
 [0.91691002 0.26877256 0.31431601 0.73129638 0.27368461]]
(2, 5)
2

In [89]:
arr=np.array([
    # [True,False],
     [32.1,43.1,45.4]
    ] ,dtype=int)
print(arr.dtype
)
arr

int64

array([[32, 43, 45]])

In [ ]:
arr=np.array([12,23,45,56,78,89,78])
print(len(arr))
print(arr.size)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])
print(arr[6])
# print(arr[7])
# negative  index also avaliable

7
7
12
23
45
56
78
89
78

In [134]:
arr=np.array([
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],
    [1,2,3,4,5,6,7,8],

])
arr[0,1] = 99
print(arr)

[[ 1 99  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7  8]]

In [138]:
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(arr[:2])

[[10 20 30 40]
 [50 60 70 80]]

In [10]:
import numpy as np
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
print(arr[2,:3])

[ 90 100 110]

In [11]:
arr[:2,:3]

array([[10, 20, 30],
       [50, 60, 70]])

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[-3:])
print(arr[::-1])

[40 50 60]
[60 50 40 30 20 10]

In [15]:
arr2=np.array([10, 20, 30, 40, 50, 60])

print(arr + arr2)

[ 20  40  60  80 100 120]

In [6]:
import numpy as np
arr= np.array([10, 20, 30, 40, 50, 60], dtype=int)
print(np.sqrt(arr))
# print(arr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]

In [8]:
import numpy as np
arr = np.array([2, 3, 4])

print(np.power(arr[1], 2))

9

In [9]:
arr=np.array([-12,-45,3,56])
print(np.abs(arr))

[12 45  3 56]

In [13]:
arr.min()
print(arr.max())

56

In [14]:
arr = np.array([10.234, 20.678, 30.456])

print(np.round(arr, 2))

[10.23 20.68 30.46]

In [ ]:
import numpy as np

sales = np.array([100, 200, 300, 400, 500])

print(np.sum(sales))
print(np.mean(sales))
print(np.median(sales))
print(np.min(sales))
print(np.max(sales))

1500
300.0
300.0
100
500

In [19]:
data = np.array([10, 20, 30, 40, 50])
print(np.var(data))

200.0

In [29]:
a = np.array([48, 49, 50, 51, 52])
b = np.array([10, 30, 50, 70, 90])
# print(np.sum(a))
# print(np.sum(b))
# print(np.var(a))
# print(np.var(b))
print(np.std(a).round(4))
print(np.std(b).round(4))

1.4142
28.2843

In [36]:
arra=np.array([1,2,3,4,5,6,7,8,9,10])
new=arra.reshape(5,2)
print(new.shape)
print(new.size)

(5, 2)
10

In [42]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1,2,3,]
])

print(arr.flatten())#flatten
print(arr.ravel())

[1 2 3 4 5 6 1 2 3]
[1 2 3 4 5 6 1 2 3]

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
# print(arr.reshape(3,4))
# print(arr.reshape(4,-1)).
# print(arr.reshape(2,6))
# print(arr.reshape(6,2))

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]]

In [52]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.append(a,b))

# result = np.hstack((a, b))

# print(result)

[1 2 3 4 5 6]

In [57]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])
# print(np.append(a,b))

# result= np.hstack((a,b))
# result= np.vstack((a,b))
result= np.concatenate((a,b))
result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
# spilt
arr=np.array([1,2,3,4,5,6,7,8])
print(np.split(arr,4))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [10]:
import numpy as np

arr= np.array([12,45,67,89,43,12])
arr1=np.where(arr>30,0,1)
arr1

array([1, 0, 0, 0, 0, 1])

In [14]:
data = np.array([23,45,56,4,2,45,])
arr1=np.where(arr>30,100,arr)
arr1[4]

np.int64(100)

In [17]:
arr1=np.array([30,50,60,70,80])
print(np.where(arr>40,"pass","fail"))

['fail' 'pass' 'pass' 'pass' 'pass' 'fail']

In [23]:
arr = np.array([10, 25, 40, 55, 70, 85])
arr1=np.where(arr==55,100,arr)
# print(arr1)
arr2=np.where(arr>=40,"pass","fail")
# print(arr2)
arr4=np.where(arr%2==0,0,arr)
print(arr4)

[ 0 25  0 55  0 85]

In [28]:
salary = np.array([20000, 35000, 50000, 18000, 70000])
arr1=np.where([salary>=30000] & [salary<30000],"high","low")
print(arr1)

TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [38]:
arr=np.array([1,2,3,4,5,55423,46,4,57,78,656])
# arr1=np.removeDuplicates
print(np.sort(arr))

[    1     2     3     4     4     5    46    57    78   656 55423]

In [45]:
a = np.array([[30, 10, 20], [90, 50, 70]])
# print(np.sort(a, axis=1)) #sort each row
print(np.sort(a,axis=0)) # sort each column

[[30 10 20]
 [90 50 70]]

In [46]:
a = np.array([[30, 10, 20], [90, 50, 70]])
print(np.argsort(a))

[[1 2 0]
 [1 2 0]]

In [49]:
a = np.array([1,2,2,3,4])
b = np.array([3,4,4,5,6])
print(np.unique(a))
print(np.intersect1d(a,b))
print(np.union1d(a,b))
print(np.setdiff1d(a,b))
print(np.setxor1d(a,b))

[1 2 3 4]
[3 4]
[1 2 3 4 5 6]
[1 2]
[1 2 5 6]

In [50]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(A * B)
print(A @ B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]

In [52]:
a = np.array([[2,1],[1,3]])
b = np.array([5,6])
x = np.linalg.solve(a,b)
print(x)

[1.8 1.4]

In [54]:
a = np.array([10, np.nan, 30, np.inf])
print(np.isnan([a]))
print(np.isfinite(a))

[[False  True False False]]
[ True False  True False]

In [66]:
a = np.array([10,20,30,40])
b = a[1:3]
print(b)
b[0] = 999
print(a)
print(a)
# print(np.shares_memory(a,b))

[20 30]
[ 10 999  30  40]
[ 10 999  30  40]

In [65]:
a = np.array([10,20,30,40])
b = a[1:3].copy()
b[0] = 999
print(a)
print(b)
print(a)

[10 20 30 40]
[999  30]
[10 20 30 40]

In [2]:
data = np.array([(1, 'A', 50000), (2, 'B', 60000)],
dtype=[('id','i4'),('name','U10'),('salary','f8')])
print(data['salary'])

[50000. 60000.]

In [ ]:
import numpy as np
rng = np.random.default_rng(42)
n = 1000
order_id = np.arange(1, n + 1)
price = rng.uniform(100, 5000, n)
quantity = rng.integers(1, 6, n)
discount = rng.uniform(0, 0.40, n)
category_id = rng.integers(1, 6, n)
rating = rng.uniform(1, 5, n)
revenue = price * quantity * (1 - discount)
# revenue


# Your tasks:
# 1. Find total revenue.
# 2. Find average order revenue.
# 3. Find highest revenue order.
# 4. Find lowest revenue order.
# 5. Find the top 10 orders using argsort.
# 6. Label orders High/Low using np.where.
# 7. Find orders with discount > 30%.
# 8. Find unique category IDs.
# 9. Calculate average revenue per category.
# 10. Replace any artificial NaN/inf values safely.
# 11. Clip rating to [1, 5].
# 12. Standardize revenue.
# 13. Select top 20 orders using advanced indexing.
# 14. Explain every shape used.

# print(revenue)
# avg=revenue//n
# print(avg)

array([14231.69334425,  1385.78229788,  7336.20560225,  8757.2422208 ,
        1516.30502552,  3893.19031343,  8103.83090351,  3225.0587637 ,
        2660.10231269,  6476.99780774,  5449.03571962,  8544.9718817 ,
        2438.82823318, 14482.92148282,  5837.50450468,  2162.31910128,
        8078.04224058,  1019.51452189, 15594.8692442 ,  8827.57455926,
        6740.20861124,  5792.57177742, 12565.88605015,  9343.56782688,
        2805.36525316,  2939.6774514 ,  8181.70855708,  1272.1430907 ,
        2416.61631915,  6139.88314806,  9860.75048529,  4594.35035824,
        1323.14185963,  5500.51894554, 11668.33037123,  4152.46500703,
        1518.41957584,  1703.62225869,  4083.77691672,  8327.07829324,
        3012.30847371, 18887.86082544, 12086.5880398 ,  6062.28250196,
        6793.59841795, 17046.2586202 ,  5418.0991124 ,  3173.66354466,
       12047.37614889,  2796.59933773,  1023.0291194 ,   224.38007035,
        6953.05354156, 14308.9800424 , 12878.7718025 ,  5454.48689217,
        5899.88991892,  9247.41458176,  1166.2048502 ,  1295.54565669,
       10133.4238948 ,  5452.02355656,  1848.31219976,  9799.13960555,
        6581.5744243 ,  6881.95213824, 10991.68162897,  7896.53611021,
         406.19007063,  5391.07845273,   963.83950085,  6496.49156333,
       10008.00764673,  1658.46796542,  1475.68214551,  4036.75704845,
        3151.6783289 ,  6628.59266407,  3407.06479003,  2565.00737791,
       10804.21672937,  1828.33783069,  6863.58066834,  3278.83406397,
         160.04736253,  1351.95589009, 12551.29692481,  7346.70453618,
        1569.44317145,  2381.5757153 ,  3901.26404954,  6861.13783395,
        7090.34407297,  1650.01768602,  1051.10923696,  9277.79407207,
        8645.51766126,  2461.61390672,  1831.77347151,  8607.28791694,
       14445.59571199, 13323.54847415,  1022.49703469,  3269.22236636,
       17736.92584308,  6427.22669646,  5655.16800095,  1282.21219676,
         947.77448811,  7480.57496354,  4194.28208145,  3011.38049026,
        5527.27371285, 12467.74970444,  2573.72673912,  7862.28370239,
       19050.86037947,  8391.27486819,  4006.81792355, 12499.01355737,
       10862.54908015, 13012.75262381,  1041.97664595,  8245.30765519,
        1023.45293249,  3534.67350433,  2922.49026701,  2988.4954594 ,
         559.23360523,  4981.53816407,  3025.7196248 , 15179.71782563,
        6570.18348019,  2605.33193131,  5453.02866037,   707.43058411,
       12068.98011918,  1553.4994669 , 10645.06452734,  1073.53279152,
        6938.77223942, 12032.50826995, 19079.72783251, 10674.78905287,
        4481.29505913,  3440.75766817,  1525.01769956,  9035.2920544 ,
        7167.89955425,   698.93690995,  7414.68727369,  7997.42433238,
        3535.04790379,  7988.20874099,  1573.68370613,  8544.48045438,
        4035.61509133,  8812.03408191, 15387.4432057 ,  7624.12567667,
        2936.27702978,  6830.37739072,  2530.41083701,  1297.08312096,
        8922.01814273,  6323.98933638,  5504.47664225, 18453.3557573 ,
        8102.73178704, 15572.1902841 ,  1338.8984245 ,  7896.8791229 ,
        4712.80641846, 17784.43650667,  1246.84372205,   799.63712017,
        1581.68953528, 12260.36505928, 11607.9684218 ,  8919.47198105,
       12539.02848937,  6016.46974223,  7401.47270787,  5833.16956617,
       14799.3293059 ,  6047.03175689,  3085.03556911,   898.24243021,
        8649.4270115 ,  3501.00940667,  6428.11040351,  2438.83507892,
        1264.56290019,  5886.41791359,  2481.14508491,  3868.47467158,
        5615.90196896, 14952.02006814,  1962.75664836,  1152.66685629,
        4948.02731039,  2947.92586981,  2194.02869187,  1199.12964145,
         409.15490644,  2966.96929835,   717.9392816 , 14281.55803361,
         905.77249219,  2287.76019847,  9593.52661369,  9984.69767029,
        2623.92353103,  2612.35168312,  3170.93132576,  5149.31905723,
        1926.53791459,  2675.30648428,  6843.16870122,  1368.48440645,
        7796.23998441,  2274.42686575,  2394.62444554, 11113.56553268,
        3616.5374023 , 18117.11193601,   954.55434129,  9222.37282993,
        6333.71033146,  2603.77977766,  1959.52121434,  2109.82824019,
       16923.72240781,  2709.34976647,  9157.07925074, 11341.25695568,
        3086.75106063,  7209.16427683,   442.7234558 ,  2184.65809727,
        7509.88608817, 14539.21274535,  3679.37386126,  1665.27887265,
        8790.90072066, 16227.78762554,  6437.98961755,  1670.45255551,
        1565.25957023,  5380.81015575,  7351.50287945, 11999.92943535,
        2997.0434235 ,  2662.86729574,  2167.03015127, 11545.16014815,
       15479.34084975,  1505.31967733,   272.2355013 ,  9508.77751925,
         707.79780808, 19303.54822659,  1483.35733491,  2327.97904404,
        4391.13893622,   885.11906177,  3612.65347756,  3309.78349932,
         630.59733372,   681.22650285,   570.45662713,  1319.37122869,
         540.64711414,  5817.57814358,  2558.11880297,  4815.22959189,
        2370.8323913 ,  2111.86894353,  7560.35771102, 13886.77055902,
        1167.11084169,  1348.21878747,  2257.29992453,  4963.24677528,
       10453.46397187,  7094.89819228,  1481.30069181,  7004.42069519,
        8764.90403766,  1738.76945708,  5807.23662805,   621.94451628,
        8460.78211316,  1697.08451499, 10771.44551851, 19946.2580251 ,
        3785.00566361, 10688.16811983,  6100.88864493, 12201.01549997,
        5921.57719545,   569.92086592,  7738.20823497,  9464.73539128,
       15704.82578302,  1721.24672067,  3856.13815359,  2655.8543203 ,
        2351.36569657,  2272.92744846,  4448.85070068,  1764.80743988,
        2613.69663193,  1720.56408496,  2532.53073442,  1332.55315961,
        1363.39380191,  8418.29398914,  6221.28436857, 14288.3391265 ,
        2886.3121746 ,  1973.21370904,  2695.1719511 ,  8271.13424417,
       12007.30570779, 16014.51130696,  6415.71105442,  2188.22853678,
        2021.06166074,  1213.49713037,  3007.67917885,  3357.88630146,
        5745.78158484, 20025.67164017,  2047.38899015,  8976.08966614,
        1697.52164661, 15121.64053628,   355.85533675,  3311.26478676,
        2290.06354813,  7408.97001831, 11327.93348037,  7505.38665003,
       11014.3053061 ,  5988.85373315,  8235.13529405,  3989.18599304,
        4996.16875392,  1181.50967808,  8494.19129465,  2395.97340481,
        9177.46346258,  6079.06993806,  3146.50640323,  3195.56839528,
       10496.86564084,  7110.8016254 ,  9039.84237186,  5437.13158758,
       14306.67285579,  1655.18387801,  2034.52381387,   418.14582025,
        9895.99852132,  1411.19986839,  4881.94500319,  3112.6776924 ,
        1368.0540505 ,  3002.22441924,  3371.12482982,  5874.10385327,
        1141.56358109,  1988.5348601 ,  2224.55739525,  2804.62854416,
       20912.28031357,  1957.51275548,  7725.99234515, 11404.05622016,
        2241.54838197, 10480.30382906, 16413.29436358,  3430.09314199,
        1684.77146057, 21409.02515885, 17164.76677266, 22007.40667281,
        2245.08963048, 17528.95271043,  8784.05049929,   485.58550281,
        9286.29059917,  6865.15285197,   420.00058534,  8645.85885082,
       15285.81349126,  2754.08299673,  4571.83307287,  8870.06688141,
        1211.92189117, 13681.17286621, 10378.41162829,  1805.95347884,
        7551.7251188 , 18119.95968458,  2454.01577766, 16320.60504087,
        1265.71715867,  3211.07527426, 10041.12189204,  3050.8829259 ,
        1733.86940416, 14029.48891474,   455.13575808,  3528.67232925,
        2357.59398755,  5547.32374905,  1628.71628673,  8468.32083008,
        5320.89600267,   975.61383332,   102.43793157,  1511.60551492,
        5587.07485016, 11859.65542483,  1090.13860508,  6098.52654057,
        1510.5229657 ,  6635.38831629,  3449.31963167,  8805.51191323,
        2427.02485078,  5684.90257044,   636.79303283,  3131.89401573,
        2307.26275992,  7805.47633366, 16914.66554725,  3132.81199343,
        7777.20322324,   703.96106507,  3087.0855295 ,  1943.98534676,
        2868.70356857, 11267.46446905, 18032.47538055,  7780.68392787,
        1457.71674562,  1965.59262294,   952.11860431, 22054.73464649,
        2485.22585388,  1740.89796964,  1751.69962458,  1833.88673247,
       19115.14766525, 11367.87908102,  7806.15053866,  2428.18271776,
        4381.08701721,  1351.51620611, 10956.99664916,  4439.17993108,
        6193.79377995,  3423.01063425,  4646.81480954, 12439.22611355,
         670.9920679 ,  4125.1096496 ,  9100.17574387,  1483.66201905,
        1450.603135  ,  1290.64893817,  1360.30294659,  4359.39547792,
        5367.24520449,  1927.37703702,  2267.13195249,  1935.52979033,
        5519.84643221,  4949.64801781,  1966.52770513,  2987.2806127 ,
         416.44303433,  2706.32841901,  4346.54686748,   871.30216841,
        5273.30784492,  5398.51598689,  6829.27947615,  4783.5320037 ,
       14244.44405978,  6409.77472543,  9617.50375123,  3898.71187873,
        9807.25278618, 13714.80984277,  1235.57788728, 10344.81657196,
        9837.1661666 ,  3649.98393376, 11418.72713097,  1899.3568473 ,
        2526.52548853,  2596.36029678,  3959.07665285, 15860.16123405,
        7101.91012938,   484.07194984,   444.50422043, 18706.67687452,
        1757.33293505,  4859.04421107,  1449.30488405,  3749.22772234,
        5819.40447652, 11073.80011056,   129.68945641, 17661.53521774,
        9532.64547627,  1840.4480563 ,  1696.00801478,  8225.34960997,
         561.04670819,  3180.97036795,  9725.16108034, 21127.29732771,
        3059.36611093,  3714.69655659, 17196.30311315, 14118.3213206 ,
        8622.50386576,  2694.31555858,   732.22651566,  3861.53310394,
        3330.67886985,  2683.0302094 ,  2080.0076218 ,  8745.8320868 ,
        8766.40548464,  9672.74295477, 15730.95557022,  6223.75335289,
        2411.61707772,  4515.01199821,  6653.81905496,  1153.6243694 ,
       10734.00755293,  1926.15326943,  5806.71265655,  1665.71038166,
        1615.94723632,  3012.92644691,  1387.39584361,  1002.80878786,
        3728.40005227, 10133.58653134,  2817.85927904,  7395.13554896,
         955.44412533,  2312.78141294, 13519.93805533,  9321.62680861,
        8174.56234626,  6375.01988004, 15334.37594921,   941.12409399,
        3400.08136683, 10949.79632429,  5769.32274542, 17390.39342007,
        8756.29947236,  5086.54783924, 14432.73749744,  4054.31264852,
        5553.73647755,  8264.54974618, 18759.96268654,  5240.73406672,
        4290.87442161,  7462.20774189,   894.55011362,  7616.05130217,
        6709.32202479,  8564.30916946,  1663.97734643,  3029.4798567 ,
        3705.07182008,   360.55148455,  3973.32702364,  3026.18713582,
        3717.86961229,  2773.15818178,   173.86635043,  1261.88417053,
       10468.78003601, 10285.20417013, 23336.96353793,  5680.52501148,
        8553.32339574,  7261.3089156 , 12261.2631762 ,  6811.47686634,
       14601.6215973 , 11258.4881156 ,  9319.34789848,   794.72421609,
        9554.62816059, 10547.22281528, 11133.10666925, 13000.61921278,
        4506.79481995, 11150.23858546,  1503.77396514,  9296.61091685,
       16877.10356516,  1769.36624569,  2705.40241858,  1358.74358873,
       17403.51842876,  4933.44984058,  4378.35447568, 10974.07602604,
       20754.69543283,  5371.81541438, 17240.58009294,   447.98151924,
       10881.9289686 ,  3989.46164428, 21283.19276968, 11521.89359549,
         848.63747932,  3632.44566528,   270.32650396,   500.29717055,
        5960.06891478,  9928.20413676,  2700.89326718, 14374.15676177,
        4779.10410788,  9975.28560732,   471.30194549,  2538.82124265,
        8276.91964176,  2704.72798683,   352.33451083,  6316.08010331,
       11828.11029099,   471.86468628,  7620.82735071, 22136.21843972,
       11731.25570657,  1720.54144204, 16238.15948326,  3559.73834694,
        4113.75833329,  2784.23000498,  9987.14906675,  2010.27561901,
        3561.83798258, 15890.69842396,   859.0974114 ,  1283.72272706,
        2301.808377  ,  9676.09184353,  5212.51540525, 20714.74873958,
        1348.64822053,  8385.1170833 ,  2566.75374819, 13082.91785443,
       19925.83902428,  3319.71077431, 12959.49103559,  4694.57910009,
       19133.89585302,  8497.40001855,  2041.55693953,  2314.13930847,
         294.42175486,   667.94388744,   248.05243257, 10945.69118377,
        7600.29314657,  4982.88998528,  2905.92914569, 11035.51440091,
       13543.18860917,  8637.82602842,  5701.61428284, 13925.58234784,
        4454.42860819,  4962.89816444, 17326.31588471,  3630.5883389 ,
        3636.40845394,  7143.16269073,  2960.36509699,  1151.46288188,
        6109.15510899,  4201.73715969,  1106.56324161, 20290.02601828,
        1295.51375962,  4362.17810755, 11349.30262974,  6485.96311985,
        8430.19886853, 11661.3652424 ,  2984.89003116,  2785.2419435 ,
       13318.31603073, 10949.68040648,  7495.4234072 ,  2916.0480418 ,
        8173.32975856,  1505.74748043,  6146.6577527 ,  4179.31983861,
        8965.02338107,  7278.02453501,   229.74691064,  8875.57652058,
        1549.63755245,  1083.0407436 ,   937.3692757 ,   409.78744731,
        6881.87995998,  5824.23496719,  7051.69212033,   774.05710819,
        3112.57533398,  2460.48449896,   833.54473504,  2286.94943935,
        3160.70251089,  1377.78965706,  5195.82491649,  3362.53869655,
          95.29642511,   633.40156505, 11067.03313335,   476.22419149,
        2190.20249144,  6905.14125362,  3101.40534756,  8291.99097473,
        9946.40915852, 18193.14377772,  2163.81718395,  1161.45015259,
        3278.84416485,  7500.99537554, 10576.96225162,  4820.1934986 ,
        5472.22091447, 12719.33180495,   660.10200127,  5859.25291287,
        2584.78927323,  1520.35451938,   542.47199262,   748.36094445,
        7135.26926899,   414.04005348,  1430.64540934,  1009.26785158,
        1368.8483856 , 10236.27081276,  3843.98095838,  2181.37009506,
        4177.80102246, 11303.74913731,   241.18333173,  8438.23969364,
        7309.54132767,  4099.03661776,  5099.18419007,  3178.76312597,
        2239.3231951 , 21279.10037023,  8045.19889587, 10981.31221352,
       22611.06086194,  1801.46958979,  5267.25246267,  1152.67241714,
        3695.18399365, 13438.62440512,  3545.23389158,  1525.7150409 ,
        5007.6143271 ,  1269.99116406,   216.7336811 ,  8846.62024918,
         684.75313909,  2685.47657892, 14585.19982557,  5056.06211617,
        9229.93053079,  3460.59848741, 18097.4129864 ,  2424.61598221,
         592.35284907,  3498.93641002,  5533.13492159,  1568.06392114,
        7868.21188326,  3177.9342874 ,   216.06354533,   351.06484667,
        4201.96159033, 13752.16117292,   620.18636366,  3979.6995211 ,
       16422.84097121,  9469.05553471,  2522.09616239,  3638.56088804,
        1029.0466687 , 14663.24583546,  1295.19021699, 16220.57772908,
       15025.87088541,   572.24038008,  5533.31616652,  5677.70604812,
       13506.25586997,  1075.44014874, 11873.53971888,  9554.1820601 ,
        2732.35135383,  9692.2338113 ,  6059.48666212,  6251.82804687,
       12454.49725321, 20958.06236132,  3330.33274554, 12744.78999189,
         450.38062871, 15559.61573672,  7511.31065345,  5571.46377166,
        1195.67367807, 13022.64027175,  6666.1840857 ,  4586.81249772,
        1604.68050156,  9531.74105385,   952.42630149,  1419.50765804,
        3904.47957933,  3569.04876644,  3780.94554996,  1637.67567738,
        8915.11335259, 14088.11816688,  4731.8212644 ,  7425.7658603 ,
        2493.53463644, 18031.6876911 , 15921.98999295,  7468.49609768,
         449.60622584,  3288.00574025,  7768.09828486,  3339.1700472 ,
        2514.55908554,  1743.57879317,  6102.95094178,   927.42095083,
       21498.39282397,  3505.08692829,  6190.73345493, 12546.76974524,
        5297.00708189,  6315.19466482, 14589.27563537, 10644.84376948,
        1391.12332173,  5518.05330719, 13203.724399  ,  2383.19420556,
        2087.85249619,  1354.26875487,  6145.42494666,   729.1043501 ,
         629.34221269,  3355.05921103,  1345.76447631, 10001.06390707,
        2215.50774613,  2910.86265448,  5778.69622994,  7997.14575629,
        5248.09173239,  4030.38375722,  3840.70162523,  4135.08706896,
        5471.36853084,  4683.46504166,  1122.74377403,  6325.17578632,
       13013.64047733, 14856.07111147,  7863.53147857,  2829.84618529,
        1160.57680464,  1937.35450009,  2798.08940659,  2682.20877118,
       11293.77968381,  7731.5322336 , 11868.60375025, 13695.01530486,
        1636.55815449,  3057.90653595,  7744.92547519,  3525.07153167,
        1093.39622745, 15633.1235914 ,  2166.33990459,  7951.99036129,
        1746.94523695,   951.69980825,  3444.89048381,  6183.11997109,
        2214.18198918, 10322.44200755,  1036.89250276,  5470.76959592,
        1595.20216287,  9992.47202064, 14005.48778544,  1374.38933981,
       14423.26935649,  2030.12048139, 18528.70851461,   412.907807  ,
        3356.19920627, 19876.13829052,  3600.83145158,  1667.64080355,
        9303.0760168 ,  1004.14824445, 10529.7704853 , 10742.35978681,
       10088.33038937,  4050.23047642,  1990.93942768,  2813.17932357,
        4830.12943993,  1826.31761893,  7060.04090981, 17470.67693202,
        2961.19496922,  7589.46375531,  6691.16253814,  6381.17336009,
        8880.8321323 ,  4871.45761316,  3593.1771177 ,   546.18387867,
       17373.20085651,  5217.31704674,  6383.43180267,  1375.04006117,
        8601.51444465,  3865.68626357,  4405.2265717 ,   161.80109312,
        1455.89210137, 18188.78916551,  1428.72059582,  9053.30599016,
        6727.52413202,  9514.93813096,  4604.11075922,  1899.64614314,
       15780.54240223,  3723.65870529, 17879.83515075, 10362.81984501,
        2288.17532436, 15616.73989946,  4899.99341716,   938.32655089,
        8494.8606256 ,  9062.18154241,  5826.97048877, 12684.87843004,
        3907.53079537,  3590.38445971, 11964.84763395,  7108.10418866,
        5034.79616871,   203.77034388, 10017.76542462,  4727.76235996])

In [18]:
import numpy as np 
ar=np.array([1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6])
aa1=np.unique_values(ar)
print(np.sort(aa1))

[0 1 2 3 4 5 6 7 8 9]

In [ ]:
arr = np.array([45, 12, 89, 34, 67, 23])
# print(np.sort(arr)[::-1])
# print(np.sort(arr))
# print(np.argmax(arr))
# print(np.argmin(arr))
# print(np.searchsorted(arr,3))

0

In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([30, 40, 50, 60, 70])
# print(np.set(a,b))
# print(np.union1d(a,b))
# print(np.intersect1d(a,b))

[30 40 50]

In [24]:
arr=np.random.rand(5)
print(arr)

[0.23963118 0.804135   0.77692401 0.68260994 0.59341013]

In [41]:
arr=np.random.randint(1,20,5)

print(np.sort(arr))

[ 2  6  8 13 16]

In [68]:
arr = np.random.randint(1, 100, (3, 4))

print(np.sort(arr,axis=1))

[[ 9 18 64 96]
 [ 7 38 85 89]
 [63 67 92 92]]

In [74]:
# Randomly selects values from an existing array.

arr = np.array([10, 20, 30, 40, 50],dtype=float)

print(np.random.choice(arr))
print(np.random.choice(arr,2)) #Select multiple:

40.0
[40. 30.]

In [76]:
np.random.seed(42)

print(np.random.randint(1, 10, 5))

[7 4 8 5 7]

In [79]:
# Modern random API

# For advanced NumPy, you'll eventually see:

# from matplotlib.pylab import number


rng = np.random.default_rng(42)

arr = rng.integers(1, 10, 5)

print(arr)

# default_rng() is the modern recommended random-number interface.

# We'll revisit it in the advanced section.

[1 7 6 4 4]

In [103]:
# 🧪 Practice

arr=np.random.rand(6)
# print(arr)

arr1=np.random.randint(1,100,20)
# print(arr1)

arr1=np.random.randint(1,100,(3,3))
# print(arr1)

arr=np.array([20,20,30,405,6,7])
print(np.random.choice(arr,3))

[405 405   6]

In [ ]:
# Array + scalar
import numpy as np

arr = np.array([10, 20, 30])

# print(arr + 50)
# print(arr-4)
# print(arr*5)
# print(arr//2)
# print(arr%5)
# print(arr**2)

[100 400 900]

In [ ]:

# 2d Array +scalar
a = np.array([
    [10, 20, 30], 
    [40, 50, 60]
])

b = np.array([1, 2, 3])

# print(a * b)
# print(a+20)
# print(a-b)
# print(a//b)
# print(a**b)

[[    10    400  27000]
 [    40   2500 216000]]

In [119]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A @ B)

[[19 22]
 [43 50]]

In [120]:
arr=np.array([
    [12,23,45,565],
    [12,34,56,67,]
    ])
print(arr.transpose())

[[ 12  12]
 [ 23  34]
 [ 45  56]
 [565  67]]

In [ ]:
marks = np.array([80, 90,np.nan , 70, 85])

# print(np.isnan(marks))

[False False  True False False]

In [126]:
arr = np.array([10, 20, np.nan, 40, np.nan])

print(np.sum(np.isnan(arr)))

2

In [127]:
x = np.inf

print(x)

inf

In [128]:
x = -np.inf

print(x)

-inf

In [129]:
arr = np.array([10, 20, np.inf, -np.inf])

print(arr)

[ 10.  20.  inf -inf]

In [132]:
prices = np.array([
    100,
    250,
    np.nan,
    500,
    np.inf,
    300
])

print(np.sum(np.isnan(prices)))

1

In [133]:
print(prices[np.isfinite(prices)])

[100. 250. 500. 300.]

In [141]:
import numpy as np
arr = np.array([
    10, 20, np.nan, 40, np.inf,
    60, np.nan, -np.inf, 80
])
# print(np.sum(np.isnan(arr)))
print(arr[~np.isnan(arr)])

[ 10.  20.  40.  inf  60. -inf  80.]

In [139]:
# print(np.sum(np.isinf(arr)))
# print(arr[~np.isnan(arr)])

In [142]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr.dtype)
print(arr.itemsize)

int64
8

In [143]:
ages = np.array(
    [21, 25, 30, 35, 40],
    dtype=np.int32
)

print("Elements:", ages.size)
print("Bytes per element:", ages.itemsize)
print("Total memory:", ages.nbytes)

Elements: 5
Bytes per element: 4
Total memory: 20

In [147]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.int32)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

5
4
20

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype=np.int32)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

5
4
20

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5], dtype=np.int64)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

5
8
40

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]

In [7]:
x = np.array([-2, -1, 0, 1, 2])

sigmoid = 1 / (1 + np.exp(-x))

print(sigmoid)

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]

In [ ]:
result = np.clip(marks, 0, 100)

print(result)

In [4]:
import numpy as np
salary = np.array([25000, 30000, 40000, 50000], dtype=int)

new_salary = salary * 1.10

print(new_salary)

[27500. 33000. 44000. 55000.]

In [9]:
marks = np.array([30, 60, 80, 40])
# vcheck= np.where(marks>=50,"pass","fail")
# vcheck

In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.einsum('ij,jk->ik',A,B)
result

array([[19, 22],
       [43, 50]])

In [14]:
# Q1 — Vectorization
x = np.array([1, 2, 3, 4, 5])

# Calculate the cube of every value without a loop.

arr= x**3
arr

array([  1,   8,  27,  64, 125])

In [15]:
price = np.array([100, 200, 300])
quantity = np.array([2, 3, 4])

# Calculate each product's revenue.

revenue = price * quantity
revenue

array([ 200,  600, 1200])

In [19]:
# Q3 — np.vectorize()

# Create:

def check(x):
    if x >= 50:
        return "Pass"
    return "Fail"

# Apply it to:

marks = np.array([30, 55, 80, 40])

# using np.vectorize().

vcheck = np.vectorize(check)
result = vcheck(marks)
result
# print(np.dtype(result))

array(['Fail', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [21]:
# Q4 — einsum()

# Given:

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Calculate the dot product using np.einsum().

# Expected:

# 140

result = np.einsum('ij,jk->ik', a, b)
result

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [24]:
# Q5 — Linear Algebra
A = np.array([
    [1, 2],
    [3, 4]
])

# Find:

# determinant
# inverse
# eigenvalues

det= np.linalg.det(A)
print(det)

inverse= np.linalg.inv(A)
print(inverse)

values,eign= np.linalg.eig(A)
print(eign)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [28]:
# Q6 — Solve equations 🔥

# Solve:

# x + 2y = 5
# 3x + 4y = 11

# using:

# np.linalg.solve()

# Expected:

a=np.array([
    [1,2],
    [3,4]
])
b = np.array([5,11],dtype=int)

c=np.linalg.solve(a,b)
print("x:",
      c)
print("y:",
      c)

# x = 1
# y = 2

x: [1. 2.]
y: [1. 2.]

In [35]:
import numpy as np

np.random.seed(42)

x = np.random.randint(1, 100, 5)

print(x)

[52 93 15 72 61]

In [34]:
rng = np.random.default_rng(42)

x = rng.integers(1, 100, 5)

print(x)

[ 9 77 65 44 43]

In [32]:
rng = np.random.default_rng(42)

names = np.array(["A", "B", "C", "D"])

result = rng.choice(names, size=3)

print(result)

['A' 'D' 'C']

In [ ]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [43]:
x = np.random.randint(1, 100, 5)
x

array([15, 62, 62, 47, 62], dtype=int32)

In [36]:
import numpy as np

data = np.array([
    ("Ravi", 25, 30000),
    ("Krishna", 28, 45000),
    ("Arjun", 24, 35000)
], dtype=[
    ("name", "U10"),
    ("age", "i4"),
    ("salary", "f8")
])
# print("salary"["salary" > 40000])
data[data["salary"] > 35000]
# print(data["name"])

array([('Krishna', 28, 45000.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('salary', '<f8')])

In [40]:
data = np.array([10, 20, -999, 40, -999, 60])
masked= np.ma.masked_equal(data,-999)
masked
print(np.sort(masked).mean())

32.5

In [47]:
date=np.datetime64("2026-10-06")
# end=np.datetime64("2026-10-01")
# result=date - end
time= date + np.timedelta64(30, "D")
print(time)

2026-11-05

In [22]:

# masked arrays allow you to handle missing or invalid data in NumPy arrays. You can create a masked array by specifying a condition that identifies the values to be masked. In this example, we will create a masked array that masks the value -999 in the data array.
import numpy as np

data = np.array([10, 20, -999, 40, 50,0,-5,4,-4,4545])  

masked = np.ma.masked_less(data, 0)
print(masked)
print(masked.mean())

# print(np.sort(masked))

[10 20 -- 40 50 0 -- 4 -- 4545]
667.0

In [23]:
import numpy as np

date = np.datetime64("2026-10-05")

print(date)

2026-10-05

In [24]:
np.timedelta64(5, "D")   # days
np.timedelta64(3, "h")   # hours
np.timedelta64(30, "m")  # minutes
np.timedelta64(20, "s")  # seconds

np.timedelta64(20,'s')

In [25]:
from numpy.polynomial import Polynomial

p = Polynomial([3, 2])

print(p(5))

13.0

In [27]:
p = Polynomial([5, 3, 2])
print(p(2))

19.0

In [28]:
p = Polynomial([5, 3, 2])

derivative = p.deriv()

print(derivative)

3.0 + 4.0 x

In [29]:
p = Polynomial([6, -5, 1])

print(p.roots())

[2. 3.]

fourier TRansforamer

In [52]:
import numpy as np

signal = np.array([1, 0, -1, 0])

result = np.fft.fft(signal)
magnitude = np.abs(result)
print(magnitude)

print(result)

[0. 2. 0. 2.]
[0.+0.j 2.+0.j 0.+0.j 2.+0.j]

In [ ]:
import time

start = time.time()
# print("Start time:", start)

Start time: 1791261008.7672198

NumPy + Pandas

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Sales": [100, 200, 300],
    "Profit": [20, 50, 80]
})

print(df)
sales = df["Sales"].to_numpy()

print(sales)
print(sales.mean())

   Sales  Profit
0    100      20
1    200      50
2    300      80
[100 200 300]
200.0

In [72]:
sales = np.array([100, 200, 300])
df=pd.DataFrame({
    "Sales": sales
    # "Profit":Profit
})
print(df)

   Sales
0    100
1    200
2    300

In [79]:
df=pd.DataFrame({
     "Sales": [5000, 15000, 8000, 20000]
})

df["Category"] = np.where(
    df["Sales"] <=4000,
    "High",
    "Low"
)
df[["Sales","Category"]]

   Sales Category
0   5000      Low
1  15000      Low
2   8000      Low
3  20000      Low

In [89]:
df["Profit"] = np.array([500, 2000, 800, 3000], dtype=int)
df["Profit"]
df["Profit_Percentage"] = (
    df["Profit"] / df["Sales"]
) * 100
data=(df[["Sales", "Profit", "Profit_Percentage"]])
data

   Sales  Profit  Profit_Percentage
0   5000     500          10.000000
1  15000    2000          13.333333
2   8000     800          10.000000
3  20000    3000          15.000000